- name: Deploy apache configuration
  synchronize:
    rsync_path: "sudo rsync"
    src:        roles/docker-proxy/files/
    dest:       /etc/apache2/
    delete:     no

- name: Deploy apache macro configuration (template)
  template:
    src:   roles/docker-proxy/templates/20-macro-docker-proxy.conf
    dest:  /etc/apache2/conf-vm/20-macro-docker-proxy.conf
    owner: vagrant
    group: root
    mode:  0644

- name: Deploy apache vhost configuration (template)
  template:
    src:   roles/docker-proxy/templates/001-proxy.conf
    dest:  /etc/apache2/sites-enabled/001-proxy.conf
    owner: vagrant
    group: root
    mode:  0644

- name: Reload apache2
  command: service apache2 restart
