- name: Install apache2
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - apache2-mpm-worker
    - libapache2-mod-macro
    - apache2-utils

- name: Enable apache modules
  command: 'a2enmod {{ item }}'
  with_items:
   - actions
   - alias
   - auth_basic
   - authn_file
   - authz_host
   - authz_user
   - autoindex
   - deflate
   - dir
   - env
   - expires
   - filter
   - headers
   - macro
   - mime
   - negotiation
   - setenvif
   - vhost_alias
   - ssl
   # Reverse proxy
   - proxy
   - proxy_http
   - rewrite

- name: Create /var/www/empty/ directory
  file:
    dest:  /var/www/empty/
    owner: vagrant
    group: vagrant
    mode:  0755
    state: directory
  ignore_errors: True

- name: Restart apache2
  command: service apache2 restart
