- name: Cleanup old orphaned docker images
  raw: 'docker images -qf "dangling=true" | xargs --no-run-if-empty docker rmi'
  when: DOCKER.cleanup.images is defined and DOCKER.cleanup.images
  ignore_errors: yes

- name: Cleanup old orphaned docker volumes
  raw: 'docker volume ls -qf "dangling=true" | xargs --no-run-if-empty docker volume rm'
  when: DOCKER.cleanup.volumes is defined and DOCKER.cleanup.volumes
  ignore_errors: yes

- name: Cleanup old temp builds
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /var/lib/docker/tmp/*
  when: DOCKER.cleanup.tmp is defined and DOCKER.cleanup.tmp
  ignore_errors: yes
